#!/bin/bash -e

dir=$(mktemp -d)

# shellcheck disable=SC2064
trap "rm -rf $dir" EXIT INT QUIT TERM

ncdu -o "$dir"/a "$1"
ncdu -o "$dir"/b "$2"
ncdu-diff "$dir"/a "$dir"/b > "$dir"/c
ncdu -f "$dir"/c
